"""Change embedding dimensions to 768

Revision ID: 6ed0b5d46358
Revises: 7d0b9f99f956
Create Date: 2025-06-21 13:45:24.830354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector  


# revision identifiers, used by Alembic.
revision: str = '6ed0b5d46358'
down_revision: Union[str, None] = '7d0b9f99f956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_entries', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_entries', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
